### ISSUE TITLE
This assumes dependency files (package.json, Gemfile) live in the root directory

### ISSUE THREAD

**Issue by gablg1** [heroku/heroku-buildpack-multi-procfile#1]
which wasn't working well for us so we implemented a similar buildpack which takes that into account https://github.com/Pagedraw/heroku-buildpack-select-subdir

**Comment by apghero** [comment]
Yes. This was built for a very specific use case, and, as it turns out doesn't apply super well generally. There's at least one other buildpack out there that does something similar to yours, based on finding this doesn't do that. :)
