### ISSUE TITLE
Error after c51247f: "FAILED to copy a Procfile"

### ISSUE THREAD

**Issue by adamnreed** [heroku/heroku-buildpack-multi-procfile#8]
Hi @apghero,

We're using this buildpack. Right after the most recent update c51247f, we are unable to deploy. Let me know if I can provide more information

Here's the error we get:
```
-----> Heroku Exec app detected
-----> Python app detected
-----> Installing requirements with pip
-----> Multi-procfile app detected
cp: ‘/tmp/build_485082aa0e49b80ed550dfea91d84ade/Procfile’ and ‘/tmp/build_485082aa0e49b80ed550dfea91d84ade/Procfile’ are the same file
      FAILED to copy a Procfile
 !     Push rejected, failed to compile Multi-procfile app.
 !     Push failed
```

**Comment by apghero** [comment]
Uh oh. Let me revert that change then. Sorry for the trouble.

**Comment by apghero** [comment]
Ok, reverted! You should be good again.

**Comment by adamnreed** [comment]
@apghero works again, thank you!

**Comment by adamnreed** [comment]
It's still trying to copy the same files btw, but ignoring the error and moving on successfully. Let me know if I can provide any other info about our stack, but we're good now!


```
-----> Heroku Exec app detected
-----> Python app detected
-----> Installing requirements with pip
-----> Multi-procfile app detected
cp: ‘/tmp/build_e9864a2e8609ead29bfa957c3f86a657/Procfile’ and ‘/tmp/build_e9864a2e8609ead29bfa957c3f86a657/Procfile’ are the same file
      Copied Procfile as Procfile successfully
-----> Discovering process types
```

**Comment by apghero** [comment]
Yeah, it's a bug. I tried to fix the bug, but should have expected people relied on the old behavior by now. Sorry for the trouble!
